#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=120:00:00
#SBATCH --partition=cpu
#SBATCH --account=ulissi
#SBATCH --job-name=vasp
#SBATCH --output=vasp.out
#SBATCH --error=std_err.txt
#SBATCH --mem-per-cpu=2G
#SBATCH --exclude=c021,f006

# --priority=TOP


module purge
# module load python/anaconda2
# source activate /home/zulissi/GASpy_conda/
module load intel/18.0.3.222 impi/2018_Update_3  cuda vasp
export PYTHONPATH=./:$PYTHONPATH
ulimit -s unlimited

export PATH="/home/zulissi/software/vasp/5.4.4_impi_cuda_patch0518_intel0818/bin/:$PATH"
export VASP_SCRIPT=./run_vasp.py
export VASP_PP_PATH=/home/katsuyut/5.4.4


# echo "import os" > run_vasp.py
# echo "exitcode = os.system('mpirun -np 16 vasp_std')" >> run_vasp.py

echo $PATH
echo $TMPDIR
echo $VASP_SCRIPT
echo $VASP_PP_PATH

python ./calc_energy.py $1